[workspace]
authors = ["Sangeetha Nandakumar <98574336+sangeethankumar@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "Intro To Python Jan 27 2026"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.0,<4"
seaborn = ">=0.13.2,<0.14"
pip = ">=25.3,<26"
pingouin = ">=0.5.5,<0.6"
scipy = ">=1.17.0,<2"
ipykernel = ">=7.1.0,<8"
jupyter = ">=1.1.1,<2"
